#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#
#Adding Simple spring security starter
#
spring.security.user.name=Animesh
spring.security.user.password=test123

#this help in getting more info about the bug during runtime
logging.level.org.springframework.security=DEBUG